matrix:
  platform:
    - amd64
    - i686

pipeline:
  build:
    image: codingworkshop/oscw-runner:latest
    commands:
      - echo "charch ${platform} && ./configure.sh && cd build-${platform}-xtchain && ninja -v && ninja diskimg -v" > build.cmds
      - xtchain < build.cmds
